var data_lang = {	
	"langCollection": [	
				{"language": "English",
				 "src": "flag_en_out.png",
				 "click": "fillTagsWithEnglish()"}, 
				{"language": "Spanish",
				 "src": "flag_mx_out.png",
				 "click": "fillTagsWithSpanish()"}, 
				{"language": "Italian",
				 "src": "flag_it_out.png",
				 "click": "fillTagsWithItalian()"}, 
				{"language": "French",
				 "src": "flag_fr_out.png",
				 "click": "fillTagsWithFrench()"}]
};
			
var data_en = {	
	"langCollection": [	
				{"language": "English",
				 "src": "flag_en_out.png",
				 "click": "fillTagsWithEnglish()"}, 
				{"language": "Spanish",
				 "src": "flag_mx_out.png",
				 "click": "fillTagsWithSpanish()"}, 
				{"language": "Italian",
				 "src": "flag_it_out.png",
				 "click": "fillTagsWithItalian()"}, 
				{"language": "French",
				 "src": "flag_fr_out.png",
				 "click": "fillTagsWithFrench()"}],
				 
	"jobTitle": "Java Web Developer Sr",
	"name": "BSCS. Jesús Alejandro Valdez Domínguez",
	"city": "México, D.F.",
	"mobile": "Mobile: 55-2107-8378",
	"email" : "janrus_2000@hotmail.com.mx",
	"createdBy": "Created by Jesús Valdez",
	
	"secTitProfile" : "Professional Profile",
	"secTitTE": "Tools Experience",
	"secTitTS": "Technical Skills",
	"secTitPE": "Professional Experience",
	"secTitCC": "Certification / Courses",
	
	"profile": "Bachelor of Science in Computer Science, graduated from the Technological Institute of Aguascalientes. Professional license 5490944.",
	"profileHighlight": "Java Web Developer with 10 years of experience in full-stack",
	"profileEnglish": "English (advanced), Italian (pre-intermediate) & French (elementary)",
	"profileVisa": "American Visa for tourism (B1/B2)",
	"profileOther": "Good team player, responsible, creative and proactive among other capabilities such as dedicated, patient and innovator.",

	"teCollection": [	
				{"name": "Java"}, 
				{"name": "Javascript"},
				{"name": "JSON"},
				{"name": "CSS"},
				{"name": "HTML"},
				{"name": "XML"},
				{"name": "MVC"},
				{"name": "Struts"},
				{"name": "Spring"},
				{"name": "Hibernate"},
				{"name": "Swagger"},
				{"name": "Eclipse"},
				{"name": "STS"},
				{"name": "Netbeans"},
				{"name": "JDeveloper"},
				{"name": "Oracle"},
				{"name": "MsSQL Server"},
				{"name": "MySQL"},
				{"name": "Mongo"},
				{"name": "Toad"},
				{"name": "PL/SQL"},
				{"name": "Maven"},
				{"name": "Gradle"},
				{"name": "JBoos"},
				{"name": "Apache Tomcat"},
				{"name": "Glashfish"},
				{"name": "SVN"},
				{"name": "Linux"},
				{"name": "Patterns"},
				{"name": "SpringBoot"},	
				{"name": "Swagger"},	
				{"name": "Docker"},	
				{"name": "GitHub"},					
				{"name": "UML"}],
	
	"tsCollection": [	
				{"name": "System analyst"}, 
				{"name": "Web Programmer (Java & Oracle)"},
				{"name": "Analysis and creation of databases (schemas, sp, triggers, others)"},
				{"name": "Data validation, migration and backup (scripts)"},
				{"name": "Installation and configuration of servers (web, mail, ftp, others)"},
				{"name": "Testing"}],
	
	"peTitleCompany": "Company",
	"peTitlePosition": "Position",
	"peTitleDuration": "Duration",	

	"peCollection": [	
				{"company": "Elektra - (Banco Azteca and Advance America) ",
				 "position": "Java Web Developer",
				 "years": "8 years",
				 "date": "2010 to date"}, 
				{"company": "Embagroup",
				 "position": "Java Web Developer",
				 "years": "7 months",
				 "date": "2009-2010"},
				{"company": "Softtek (General Electric-Corporate)",
				 "position": "Java Web Developer & DBA",
				 "years": "2 years",
				 "date": "2007-2009"},
				{"company": "Electoral Federal Institute",
				 "position": "Delphi Developer & DBA",
				 "years": "6 months",
				 "date": "2006"},
				{"company": "ITESM Campus Aguascalientes",
				 "position": "IT Support & Developer",
				 "years": "5 years",
				 "date": "2001-2006"}],
	
	"ccTitleName": "Course Name",
	"ccTitleCompany": "Company",
	"ccTitlePlace": "Place",
	"ccTitleDate": "Date",
	
	"ccCollection": [	
				{"name": "English",
				 "company": "Modern Language Center",
				 "place": "México, D.F.",
				 "date": "2018"}, 
				{"name": "Java 8",
				 "company": "Netec",
				 "place": "México, D.F.",
				 "date": "2018"},
				{"name": "Scrum Team Member",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Agile Scrum Day",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},				 
				{"name": "Spring CTFRM03",
				 "company": "Qualtrain Express",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Telecommunications",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2012"},
				{"name": "Best practices for Java",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2011"},
				{"name": "SQL practical solutions",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2010"},
				{"name": "Niagara AX Certified",
				 "company": "TRIDIUM",
				 "place": "Richmond, VA.",
				 "date": "2009"},
				{"name": "Sun Certified Java Programmer 5",
				 "company": "Desarrolla",
				 "place": "Aguascalientes, Mex.",
				 "date": "2009"}]	
}

var data_es = {	
	"langCollection": [	
				{"language": "Inglés",
				 "src": "flag_en_out.png",
				 "click": "fillTagsWithEnglish()"}, 
				{"language": "Español",
				 "src": "flag_mx_out.png",
				 "click": "fillTagsWithSpanish()"}, 
				{"language": "Italiano",
				 "src": "flag_it_out.png",
				 "click": "fillTagsWithItalian()"}, 
				{"language": "Francés",
				 "src": "flag_fr_out.png",
				 "click": "fillTagsWithFrench()"}],

	"jobTitle": "Desarrollador Java Web Sr",
	"name": "LI. Jesús Alejandro Valdez Domínguez",
	"city": "México, D.F.",
	"mobile": "Celular: 55-2107-8378",
	"email" : "janrus_2000@hotmail.com.mx",
	"createdBy": "Creado por Jesús Valdez",

	"secTitProfile" : "Perfil Profesional",
	"secTitTE": "Experiencia en Tecnologías",
	"secTitTS": "Conocimientos Técnicos",
	"secTitPE": "Experiencia Profesional",
	"secTitCC": "Certificaciones / Cursos",
	
	"profile": "Licenciado en Informática, egresado del Instituo Tecnológico de Aguascalientes. Cédula profesional 5490944.",
	"profileHighlight": "Desarrollador Java Web con 10 años de experiencia en full-stack",
	"profileEnglish": "Inglés (avanzado), Italiano (pre-intermedio), Francés (básico)",
	"profileVisa": "Visa de USA para turismo (B1/B2)",
	"profileOther": "Trabajo en equipo, responsable, creativo y proactivo entre otras habilidades como dedicado, paciente and innovador.",
	
	"teCollection": [	
				{"name": "Java"}, 
				{"name": "Javascript"},
				{"name": "JSON"},
				{"name": "CSS"},
				{"name": "HTML"},
				{"name": "XML"},
				{"name": "MVC"},
				{"name": "Struts"},
				{"name": "Spring"},
				{"name": "Hibernate"},
				{"name": "Swagger"},
				{"name": "Eclipse"},
				{"name": "STS"},
				{"name": "Netbeans"},
				{"name": "JDeveloper"},
				{"name": "Oracle"},
				{"name": "MsSQL Server"},
				{"name": "MySQL"},
				{"name": "Mongo"},
				{"name": "Toad"},
				{"name": "PL/SQL"},
				{"name": "Maven"},
				{"name": "Gradle"},
				{"name": "JBoos"},
				{"name": "Apache Tomcat"},
				{"name": "Glashfish"},
				{"name": "SVN"},
				{"name": "Linux"},
				{"name": "Patterns"},
				{"name": "SpringBoot"},	
				{"name": "Swagger"},	
				{"name": "Docker"},	
				{"name": "GitHub"},					
				{"name": "UML"}],	
	
	"tsCollection": [	
				{"name": "Análista de Sistemas"}, 
				{"name": "Programador Web (Java & Oracle)"},
				{"name": "Análisis y creación de bases de datos (schemas, sp, triggers, otros)"},
				{"name": "Validación de datos, migración y respaldos (scripts)"},
				{"name": "Instalación y configuración de servidores (web, mail, ftp, otros)"},
				{"name": "Pruebas de QA"}],

	"peTitleCompany": "Compañia",
	"peTitlePosition": "Puesto",
	"peTitleDuration": "Duración",	

	"peCollection": [	
				{"company": "Elektra - (Banco Azteca and Advance America) ",
				 "position": "Desarrollador Java Web",
				 "years": "8 años",
				 "date": "2010 a la fecha"}, 
				{"company": "Embagroup",
				 "position": "Desarrollador Java Web",
				 "years": "7 meses",
				 "date": "2009-2010"},
				{"company": "Softtek (General Electric-Corporate)",
				 "position": "Desarrollador Java Web & DBA",
				 "years": "2 años",
				 "date": "2007-2009"},
				{"company": "Instituto Federal Electoral",
				 "position": "Desarrollador Delphi & DBA",
				 "years": "6 meses",
				 "date": "2006"},
				{"company": "ITESM Campus Aguascalientes",
				 "position": "Desarrollador y soporte de TI",
				 "years": "5 años",
				 "date": "2001-2006"}],
				
	"ccTitleName": "Nombre del Curso",
	"ccTitleCompany": "Compañia",
	"ccTitlePlace": "Lugar",
	"ccTitleDate": "Fecha",				
				
	"ccCollection": [	
				{"name": "Inglés",
				 "company": "Modern Language Center",
				 "place": "México, D.F.",
				 "date": "2018"}, 
				{"name": "Java 8",
				 "company": "Netec",
				 "place": "México, D.F.",
				 "date": "2018"},
				{"name": "Scrum Team Member",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Agile Scrum Day",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},				 
				{"name": "Spring CTFRM03",
				 "company": "Qualtrain Express",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Telecomunicaciones",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2012"},
				{"name": "Best practices for Java",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2011"},
				{"name": "SQL practical solutions",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2010"},
				{"name": "Niagara AX Certified",
				 "company": "TRIDIUM",
				 "place": "Richmond, VA.",
				 "date": "2009"},
				{"name": "Sun Certified Java Programmer 5",
				 "company": "Desarrolla",
				 "place": "Aguascalientes, Mex.",
				 "date": "2009"}]	
}

//"Strumenti esperienza"
var data_it = {	

	"langCollection": [	
				{"language": "Inglese",
				 "src": "flag_en_out.png",
				 "click": "fillTagsWithEnglish()"}, 
				{"language": "Spagnolo",
				 "src": "flag_mx_out.png",
				 "click": "fillTagsWithSpanish()"}, 
				{"language": "Italiano",
				 "src": "flag_it_out.png",
				 "click": "fillTagsWithItalian()"}, 
				{"language": "Francese",
				 "src": "flag_fr_out.png",
				 "click": "fillTagsWithFrench()"}],
				 
	"jobTitle": "Java Web Developer Sr",
	"name": "BSCS. Jesús Alejandro Valdez Domínguez",
	"city": "México, D.F.",
	"mobile": "Cellulare: 55-2107-8378",
	"email" : "janrus_2000@hotmail.com.mx",
	"createdBy": "Creato da Jesús Valdez",
	
	"secTitProfile" : "Profilo Professionale",
	"secTitTE": "Conoscenze",
	"secTitTS": "Abilità tecniche",
	"secTitPE": "Esperienza professionale",
	"secTitCC": "Certificazione / Corsi",
	
	"profile": "Laurea in Informatica, laureata presso l'Istituto Tecnologico di Aguascalientes. Licenza professionale 5490944.",
	"profileHighlight": "Java Web Developer con 10 anni di esperienza nello full-stack",
	"profileEnglish": "Inglese (avanzato), Italiano (pre-intermedio) e Francese (elementare)",
	"profileVisa": "Visto americano per turismo (B1 / B2)",
	"profileOther": "Buon giocatore di squadra, responsabile, creativo e propositivo tra le altre capacità come dedicato, paziente e innovatore.",
	
	"teCollection": [	
				{"name": "Java"}, 
				{"name": "Javascript"},
				{"name": "JSON"},
				{"name": "CSS"},
				{"name": "HTML"},
				{"name": "XML"},
				{"name": "MVC"},
				{"name": "Struts"},
				{"name": "Spring"},
				{"name": "Hibernate"},
				{"name": "Swagger"},
				{"name": "Eclipse"},
				{"name": "STS"},
				{"name": "Netbeans"},
				{"name": "JDeveloper"},
				{"name": "Oracle"},
				{"name": "MsSQL Server"},
				{"name": "MySQL"},
				{"name": "Mongo"},
				{"name": "Toad"},
				{"name": "PL/SQL"},
				{"name": "Maven"},
				{"name": "Gradle"},
				{"name": "JBoos"},
				{"name": "Apache Tomcat"},
				{"name": "Glashfish"},
				{"name": "SVN"},
				{"name": "Linux"},
				{"name": "Patterns"},
				{"name": "SpringBoot"},	
				{"name": "Swagger"},	
				{"name": "Docker"},	
				{"name": "GitHub"},					
				{"name": "UML"}],	
	
	"tsCollection": [	
				{"name": "Analista di sistema"}, 
				{"name": "Programmatore Web (Java e Oracle)"},
				{"name": "Analisi e creazione di database (schemi, sp, trigger, altri)"},
				{"name": "Convalida dei dati, migrazione e backup (script)"},
				{"name": "Installazione e configurazione di server (web, mail, ftp, altri)"},
				{"name": "Test del QA"}],

	"peTitleCompany": "Azienda",
	"peTitlePosition": "Posizione",
	"peTitleDuration": "Durata",	

	"peCollection": [	
				{"company": "Elektra - (Banco Azteca e Advance America) ",
				 "position": "Java Web Developer",
				 "years": "8 anni",
				 "date": "2010 to date"}, 
				{"company": "Embagroup",
				 "position": "Java Web Developer",
				 "years": "7 mesi",
				 "date": "2009-2010"},
				{"company": "Softtek (General Electric-Corporate)",
				 "position": "Java Web Developer & DBA",
				 "years": "2 anni",
				 "date": "2007-2009"},
				{"company": "Istituto Federale Elettorale",
				 "position": "Delphi Developer & DBA",
				 "years": "6 mesi",
				 "date": "2006"},
				{"company": "ITESM Campus Aguascalientes",
				 "position": "IT Support & Developer",
				 "years": "5 anni",
				 "date": "2001-2006"}],
				
	"ccTitleName": "Nome del corso",
	"ccTitleCompany": "Azienda",
	"ccTitlePlace": "Posto",
	"ccTitleDate": "Data",				
				
	"ccCollection": [	
				{"name": "Inglese",
				 "company": "Modern Language Center",
				 "place": "México, D.F.",
				 "date": "2018"}, 
				{"name": "Java 8",
				 "company": "Netec",
				 "place": "México, D.F.",
				 "date": "2018"},
				{"name": "Scrum Team Member",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Agile Scrum Day",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},				 
				{"name": "Spring CTFRM03",
				 "company": "Qualtrain Express",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Telecomunicazioni",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2012"},
				{"name": "Best practices per Java",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2011"},
				{"name": "Soluzioni pratiche SQL",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2010"},
				{"name": "Certificato Niagara AX",
				 "company": "TRIDIUM",
				 "place": "Richmond, VA.",
				 "date": "2009"},
				{"name": "Programmatore Java certificato Sun 5",
				 "company": "Desarrolla",
				 "place": "Aguascalientes, Mex.",
				 "date": "2009"}]		
}

//"Outils d'expérience"
//"Compétences techniques"
//Informatique
var data_fr = {	
	"langCollection": [	
				{"language": "Anglais",
				 "src": "flag_en_out.png",
				 "click": "fillTagsWithEnglish()"}, 
				{"language": "Espanol",
				 "src": "flag_mx_out.png",
				 "click": "fillTagsWithSpanish()"}, 
				{"language": "Italien",
				 "src": "flag_it_out.png",
				 "click": "fillTagsWithItalian()"}, 
				{"language": "Français",
				 "src": "flag_fr_out.png",
				 "click": "fillTagsWithFrench()"}],

	"jobTitle": "Desarrollador Java Web Sr",
	"name": "LI. Jesús Alejandro Valdez Domínguez",
	"city": "México, D.F.",
	"mobile": "Portable telephone: 55-2107-8378",
	"email" : "janrus_2000@hotmail.com.mx",
	"createdBy": "Créé par Jesús Valdez",

	"secTitProfile" : "Profil Pro",
	"secTitTE": "Compétences",
	"secTitTS": "Connaissances",
	"secTitPE": "Expérience professionnelle",
	"secTitCC": "Certification / Cours",
	
	"profile": "Bachelor of Science en informatique, diplômé de l'Institut Technologique d'Aguascalientes. Licence professionnelle 5490944.",
	"profileHighlight": "Java Web Developer avec 10 ans d'expérience en full-stack",
	"profileEnglish": "Anglais (avancé), Italien (pré-intermédiaire) et Français (élémentaire)",
	"profileVisa": "Visa américain pour le tourisme (B1 / B2)",
	"profileOther": "Bon joueur d'équipe, responsable, créatif et proactif parmi d'autres capacités telles que dédié, patient et innovateur.",
	
	"teCollection": [	
				{"name": "Java"}, 
				{"name": "Javascript"},
				{"name": "JSON"},
				{"name": "CSS"},
				{"name": "HTML"},
				{"name": "XML"},
				{"name": "MVC"},
				{"name": "Struts"},
				{"name": "Spring"},
				{"name": "Hibernate"},
				{"name": "Swagger"},
				{"name": "Eclipse"},
				{"name": "STS"},
				{"name": "Netbeans"},
				{"name": "JDeveloper"},
				{"name": "Oracle"},
				{"name": "MsSQL Server"},
				{"name": "MySQL"},
				{"name": "Mongo"},
				{"name": "Toad"},
				{"name": "PL/SQL"},
				{"name": "Maven"},
				{"name": "Gradle"},
				{"name": "JBoos"},
				{"name": "Apache Tomcat"},
				{"name": "Glashfish"},
				{"name": "SVN"},
				{"name": "Linux"},
				{"name": "Patterns"},
				{"name": "SpringBoot"},	
				{"name": "Swagger"},	
				{"name": "Docker"},	
				{"name": "GitHub"},					
				{"name": "UML"}],
	
	"tsCollection": [	
				{"name": "Analyste de système"}, 
				{"name": "Programmeur Web (Java et Oracle)"},
				{"name": "Analyse et création de bases de données (schémas, sp, triggers, autres)"},
				{"name": "Validation des données, migration et sauvegarde (scripts)"},
				{"name": "Installation et configuration des serveurs (web, mail, ftp, autres)"},
				{"name": "Test d'assurance qualité"}],
	
	"peTitleCompany": "Nom de l'entreprise",
	"peTitlePosition": "Position",
	"peTitleDuration": "Durée",	

	"peCollection": [	
				{"company": "Elektra - (Banco Azteca and Advance America) ",
				 "position": "Java Web Developer",
				 "years": "8 années",
				 "date": "2010 to date"}, 
				{"company": "Embagroup",
				 "position": "Java Web Developer",
				 "years": "7 mois",
				 "date": "2009-2010"},
				{"company": "Softtek (General Electric-Corporate)",
				 "position": "Java Web Developer & DBA",
				 "years": "2 années",
				 "date": "2007-2009"},
				{"company": "Electoral Federal Institute",
				 "position": "Delphi Developer & DBA",
				 "years": "6 mois",
				 "date": "2006"},
				{"company": "ITESM Campus Aguascalientes",
				 "position": "IT Support & Developer",
				 "years": "5 années",
				 "date": "2001-2006"}],
	
	"ccTitleName": "Nom du cours",
	"ccTitleCompany": "Compagnie",
	"ccTitlePlace": "Endroit",
	"ccTitleDate": "date",
	
	"ccCollection": [	
				{"name": "Anglais",
				 "company": "Modern Language Center",
				 "place": "México, D.F.",
				 "date": "2018"}, 
				{"name": "Java 8",
				 "company": "Netec",
				 "place": "México, D.F.",
				 "date": "2018"},
				{"name": "Scrum Team Member",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Agile Scrum Day",
				 "company": "Qualtop",
				 "place": "México, D.F.",
				 "date": "2017"},				 
				{"name": "Spring CTFRM03",
				 "company": "Qualtrain Express",
				 "place": "México, D.F.",
				 "date": "2017"},
				{"name": "Télécommunications",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2012"},
				{"name": "Meilleures pratiques pour Java",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2011"},
				{"name": "Solutions pratiques SQL",
				 "company": "Aster",
				 "place": "México, D.F.",
				 "date": "2010"},
				{"name": "Certifié Niagara AX",
				 "company": "TRIDIUM",
				 "place": "Richmond, VA.",
				 "date": "2009"},
				{"name": "Programmeur Java certifié Sun 5",
				 "company": "Desarrolla",
				 "place": "Aguascalientes, Mex.",
				 "date": "2009"}]	
}
